import pandas as pd
import geopandas as gpd
import os

# --- PATHS (Update these if different) ---
CSV_INPUT = r"C:\Users\FlawiyaShirishMore\Downloads\Africa-Drought-Study\Africa_Maize_Drought_Annual_MultiThreshold.csv"  # The file generated by your script
GADM_GPKG = r"C:\Users\FlawiyaShirishMore\Downloads\Africa-Drought-Study\data\gadm_410-levels\gadm_410-levels.gpkg"
OUTPUT_FILE = "drought_annual_Multithreshold_with_gadm_metadata.csv"

def enhance_drought_data():
    print("1. Loading drought results...")
    if not os.path.exists(CSV_INPUT):
        print(f"Error: {CSV_INPUT} not found. Please run your analysis script first.")
        return
    
    df_results = pd.read_csv(CSV_INPUT)
    # Standardize name for merging
    df_results['match_id'] = df_results['feature_id'].astype(str).str.strip().str.upper()

    print("2. Loading GADM Level 2 metadata (this may take a minute)...")
    # We load 'ADM_2' because it contains the County/District level info (NAME_2)
    try:
        gdf_gadm = gpd.read_file(GADM_GPKG, layer='ADM_2')
    except Exception as e:
        print(f"Error loading layer ADM_2: {e}")
        print("Attempting layer 'adm2' or checking available layers...")
        return

    # Standardize GADM names for merging
    # Note: We use NAME_2 because your script used district-level polygons
    gdf_gadm['match_name'] = gdf_gadm['NAME_2'].astype(str).str.strip().str.upper()

    print("3. Merging drought results with GADM metadata...")
    # Select only the columns requested by your colleague
    # GADM 4.1 columns: COUNTRY, GID_0, NAME_1, NAME_2, GID_2
    gadm_metadata = gdf_gadm[[
        'match_name', 
        'COUNTRY',   # Full country name
        'GID_0',     # Country Code (e.g., AGO)
        'NAME_1',    # Region Name
        'NAME_2',    # County/District Name
        'GID_2'      # Unique GID for the district
    ]].copy()

    # Perform the merge
    final_df = pd.merge(
        df_results, 
        gadm_metadata, 
        left_on='match_id', 
        right_on='match_name', 
        how='left'
    )

    print("4. Formatting columns to colleague's specification...")
    # Map to specific requested names
    final_df = final_df.rename(columns={
        'COUNTRY': 'country',
        'GID_2': 'gadm_id',    # The unique code from GADM
        'GID_0': 'gad0',       # Country code
        'NAME_1': 'gad1',      # Region name
        'NAME_2': 'gad2'       # County name
    })

    # Drop the temporary matching columns and the old feature_id if desired
    # Or keep feature_id as it was your original reference
    final_df = final_df.drop(columns=['match_id', 'match_name'])

    # Reorder columns to put location first
    cols_to_move = ['country', 'gadm_id', 'gad0', 'gad1', 'gad2']
    other_cols = [c for c in final_df.columns if c not in cols_to_move]
    final_df = final_df[cols_to_move + other_cols]

    # Handle missing matches
    missing_count = final_df['gadm_id'].isna().sum()
    if missing_count > 0:
        print(f"⚠️ Warning: {missing_count} rows could not be matched to GADM. Check for spelling differences.")
    
    print(f"5. Saving to {OUTPUT_FILE}...")
    final_df.to_csv(OUTPUT_FILE, index=False)
    print("✅ Done!")

if __name__ == "__main__":
    enhance_drought_data()